const resMenu = 
[
    {
        "id":1,
        "name":"Meghana Foods",
        "cuisines": ["South Indian, North Indian, Asian"],
        "rating": "4.5",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://norecipes.com/wp-content/uploads/2017/05/chicken-biryani-006.jpg",
        "itemCards": 
        [
            {name: "Lemon Rice", price: 120, description: 'Serves 1'},
            {name: "Biryani with Chicken kabob", price: 220, description: 'Serves 2' },
            {name: "Vegetable Biryani", price: 180, description: 'Serves 1' },
            {name: "Peas Pulav", price: 140, description: 'Serves 1' },
            {name: "Mutton Biryani", price: 220, description: 'Serves 1' },
            {name: "Prawns Biryani", price: 250, description: 'Serves 1' },
            {name: "Fish Biryani", price: 230, description: 'Serves 1' },
        ],
        // "itemCards": {name: "Chicken Biryani", price: 220, description: 'Serves 2' },
    },
    {
        "id":2,
        "name":"KFC",
        "cuisines": ["Fast Foods"],
        "rating": "4.0",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹600",
        "iamge":"https://vegconomist.com/wp-content/uploads/sites/3/Meat-Zero-KFC-973x1024.jpg",
        "itemCards": [
            {name: "Chicken Fry", price: 220, description: 'Serves 2'  },
            {name: "Chicken Grill", price: 220, description: 'Serves 2'  },
            {name: "Chicken Kabob", price: 220, description: 'Serves 2'  },
            {name: "Smoked Chicken Grill", price: 220, description: 'Serves 2'  },
            {name: "Masala Fries", price: 220, description: 'Serves 2'  },
            {name: "French Fries", price: 220, description: 'Serves 2'  },
            {name: "Coke", price: 220, description: 'Serves 2'  },
        ],
    },
    {
        "id":3,
        "name":"Katmandu Momos",
        "cuisines": ["Nepali, Chinese"],
        "rating": "4.1",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹300",
        "iamge":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVssjlTD0F8nWrqblFYcFrgwZlwy7aGwAJQA&s",
        "itemCards": [
            {name: "Paneer Momos", price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos", price: 220, description: 'Serves 2'  },
            {name: "Chana Masala", price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan", price: 220, description: 'Serves 2'  },
            {name: "Rotis", price: 220, description: 'Serves 2'  },
            {name: "Butter Naan", price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry", price: 220, description: 'Serves 2' },
        ]
    },
    {
        "id":4,
        "name":"Curry Pizza",
        "cuisines": ["Italian"],
        "rating": "4.2",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹800",
        "iamge":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAuPL8vte4MuDzZN8eY9UDLKOdB74mUUhQoA&s",
        "itemCards": [
            {name: "Paneer Momos", price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos", price: 220, description: 'Serves 2'  },
            {name: "Chana Masala", price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan", price: 220, description: 'Serves 2'  },
            {name: "Rotis", price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2' },
            {name: "Bamboo Curry", price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":5,
        "name":"Paradise",
        "cuisines": ["South Indian, Biryani, Asian"],
        "rating": "4.5",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmL-wW82KGwI4HHCklJuOMFRFJDygcSAPbtQ&s",
        "itemCards": [
            {name: "Paneer Momos", price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos", price: 220, description: 'Serves 2'  },
            {name: "Chana Masala", price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan", price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2' },
            {name: "Butter Naan", price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2' },
        ]
    },
    {
        "id":6,
        "name":"Cakes N Bakes",
        "cuisines": ["South Indian Snacks, Bakery"],
        "rating": "4.5",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5uwMHeR0jpyDB0JWAF0P1vupAH41Jdq3jmQ&s",
        "itemCards": [
            {name: "Paneer Momos", price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2' },
            {name: "Chana Masala",  price: 220, description: 'Serves 2' },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2' },
            {name: "Rotis",  price: 220, description: 'Serves 2' },
            {name: "Butter Naan",  price: 220, description: 'Serves 2' },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2' },
        ]
    },
    {
        "id":7,
        "name":"85 degree",
        "cuisines": ["American Bakery"],
        "rating": "4.0",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://www.blessthismessplease.com/wp-content/uploads/2015/05/cream-puff-recipe-2.jpg",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":8,
        "name":"Haleluya Ethiopian Gourmet",
        "cuisines": ["Ethiopian"],
        "rating": "4.5",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://migrationology.com/wp-content/uploads/2014/02/ethiopian-food.jpg",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",   price: 220, description: 'Serves 2' },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":9,
        "name":"Sala Thai Kichen",
        "cuisines": ["Thai"],
        "rating": "3.5",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://media.cnn.com/api/v1/images/stellar/prod/151215114545-40-thai-food-27-som-tam-1.jpg?q=w_1900,h_1096,x_0,y_0,c_fill",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":10,
        "name":"Panda Food Express",
        "cuisines": ["Chinese"],
        "rating": "4.5",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2022/07/07/GettyImages-1353886090_s4x3.jpg.rend.hgtvcom.1280.960.suffix/1657224547659.jpeg",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":11,
        "name":"Sushi Ken",
        "cuisines": ["Japanese"],
        "rating": "3.9",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsx8g11Tazb1ENNS-axEmJsNT-Yb329ZqN3Q&s",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",   price: 220, description: 'Serves 2' },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":12,
        "name":"Rajwadi Thali",
        "cuisines": ["North Indian"],
        "rating": "4.9",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr9SpIIKsSq6WNp8NXWksekYA0fGx71aC3sg&s",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",   price: 220, description: 'Serves 2' },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":13,
        "name":"Banana Leaf",
        "cuisines": ["Malaysian, South Indian"],
        "rating": "3.9",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://www.beyondkimchee.com/wp-content/uploads/2022/06/Pineapple-Fried-Rice-thumbnail-1.jpg",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",  price: 220, description: 'Serves 2'  },
        ]
    },
    {
        "id":14,
        "name":"Ramen Shu",
        "cuisines": ["Japanese"],
        "rating": "3.6",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹500",
        "iamge":"https://rimage.gnst.jp/livejapan.com/public/article/detail/a/00/00/a0000352/img/basic/a0000352_main.jpg",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",   price: 220, description: 'Serves 2' },
        ]
    },
    {
        "id":15,
        "name":"Dosa Hut",
        "cuisines": ["South Asian"],
        "rating": "4.1",
        "deliveryTime": "30-40 mins",
        "costForTwo": "₹200",
        "iamge":"https://www.cookwithmanali.com/wp-content/uploads/2020/05/Masala-Dosa.jpg",
        "itemCards": [
            {name: "Paneer Momos",  price: 220, description: 'Serves 2'  },
            {name: "Vegetable Momos",  price: 220, description: 'Serves 2'  },
            {name: "Chana Masala",  price: 220, description: 'Serves 2'  },
            {name: "Garlic Naan",  price: 220, description: 'Serves 2'  },
            {name: "Rotis",  price: 220, description: 'Serves 2'  },
            {name: "Butter Naan",  price: 220, description: 'Serves 2'  },
            {name: "Bamboo Curry",   price: 220, description: 'Serves 2' },
        ]
    }
]

export default resMenu;